name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Build Image
        run: |
          docker buildx build -t thepeoplesbot:${{ github.sha }} .

