name: Create Tag for Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
 
jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email ""      

      - name: Create Release
        run: |
          git tag v${{ github.run_number }}
          git push origin --tags
          